version: "3.8"

services:
  msa_front:
    container_name: msa_front
    image: ubiqube/msa2-front:4ce4ec3fa88e90f4f59b594d5033e4cb09a457b1
    depends_on:
      - msa_api
      - msa_ui
      - camunda
      - msa_ai_ml
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 8043
        published: 443
        protocol: tcp
        mode: host
      - target: 8514
        published: 514
        protocol: udp
        mode: host
      - target: 8162
        published: 162
        protocol: udp
        mode: host
      - target: 8069
        published: 69
        protocol: udp
        mode: host
      - "5200-5200:5200-5200/udp"
   #
    # uncomment one of the 2 sections below when installing a custom certificate 
    # - Docker standard standalone installation
    #volumes:
    #    - "msa_front:/etc/nginx/ssl"
    # - Docker Swarm HA installation
    #volumes:
    #    - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"
  db:
    container_name: msa_db
    image: ubiqube/msa2-db:92e19c6e051e1bbaba4948741fd8f553aff4e407
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
      CAMUNDA_PASSWORD: camunda
      CAMUNDA_DB: process-engine
      CAMUNDA_USER: camunda
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    container_name: msa_api
    image: ubiqube/msa2-api:34ada046dbec68d7b16af574dc2426915ccea759
    depends_on:
      - db
      - msa_es
    environment:
      - "ES_CREDENTIALS=c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc="
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_dev:/opt/devops/"
      - "msa_api_logs:/opt/jboss/wildfly/standalone/log"
      - "msa_api_logs:/opt/wildfly/logs/processLog"

  msa_ui:
    container_name: msa_ui
    image: ubiqube/msa2-ui:3656dbb4dd1df393d0b82a7b8fba1eb0a1d13418
    depends_on:
      - msa_api
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true
    - FEATURE_MONITORING_PROFILES=true
    - FEATURE_SCHEDULE_WORKFLOWS=true
    - FEATURE_PROFILE_AUDIT_LOGS=true
    - FEATURE_PERMISSION_PROFILES=true
    - FEATURE_AI_ML=false

  msa_sms:
    container_name: msa_sms
    image: ubiqube/msa2-sms:d2b9b06b8299ac8c4bddb1d27e12ebf765757356
    environment:
      - ES_CREDENTIALS=c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
    cap_add:
      - NET_ADMIN
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "msa_dev:/opt/devops/"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_sms_logs:/opt/sms/logs"
      - "msa_svn:/opt/svnroot"

  msa_bud:
    container_name: msa_bud
    image: ubiqube/msa2-bud:7228d5d1d41da4f0c146275ea8c3ffbdcb8d70eb
    depends_on:
      - db
    volumes:
      - "msa_bud_logs:/opt/bud/logs/"

  msa_alarm:
    container_name: msa_alarm
    image: ubiqube/msa2-alarm:f6755354e561918383506adcb0df9b90274c4530
    depends_on:
      - db
      - msa_es
    environment:
      - "ES_CREDENTIALS=c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc="
  
  camunda:
    depends_on:
      - db
    image: ubiqube/msa2-camunda:e8cd089949cdf40b3bb40709b51fbc0edd213a04
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: 'jdbc:postgresql://db:5432/process-engine'
      DB_USERNAME: camunda
      DB_PASSWORD: camunda
      DB_VALIDATE_ON_BORROW: 'true'
      WAIT_FOR: 'db:5432'
      WAIT_FOR_TIMEOUT: 60

  msa_es:
    container_name: msa_es
    image: ubiqube/msa2-es:38622cf63d1378a5f9606fce2336de4cf6b7b512
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_CREDENTIALS=c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc="
    volumes:
      - "msa_es:/usr/share/elasticsearch/data"

  msa_cerebro:
    image: ubiqube/msa2-cerebro:bc1ea10586035ad1c1fcb1e2145d049c1e3449fe
    environment:
      AUTH_TYPE: basic
      BASIC_AUTH_USER: cerebro
      BASIC_AUTH_PWD: "N@X{M4tfw'5%)+35"
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
    - "9000:9000"
  
  msa_kibana:
    container_name: msa_kibana
    image: ubiqube/msa2-kibana:9453bc6a0a2f7f8a4a0f7d881d8743325bb5f30a
    depends_on:
      - msa_es
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://msa_es:9200
      - ELASTICSEARCH_HOSTS=http://msa_es:9200
      - "ES_CREDENTIALS=c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc="
    networks:
      default:
        aliases:
          - "msa-kibana"
          
  msa_ai_ml:
    image: ubiqube/msa2-ai-ml:15db86c6b212ae4ccf7c49eac086659c53f903b2
    ports:
      - "8000:8000"
    volumes:
      - "msa_ai_ml_db:/msa_proj/database"
    networks:
      default:
        aliases:
          - "msa-ai-ml"

  msa_dev:
    container_name: msa_dev
    #build: ./lab/msa_dev
    image: ubiqube/msa2-linuxdev:1f16359514fcc22ad0ff73d918b1eccd6272144f
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_dev:/opt/devops/"
      
  linux_me:
    container_name: linux_me
    # use local image for quickstart dev => for release: make sure the changes are ported to msa-docker and uncomment the line below
    image: ubiqube/msa2-linuxme:b831acacdef579420ee1abf70ef66655d969fcbb
    #build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - DAC_READ_SEARCH
      - sys_rawio
    ports:
      - "2224:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
    privileged: true

  linux_me_2:
    container_name: linux_me_2
    # use local image for quickstart dev => for release: make sure the changes are ported to msa-docker and uncomment the line below
    image: ubiqube/msa2-linuxme:7fc20ffaef77c39f402b6fcaa81b24540ee35850
    #build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - DAC_READ_SEARCH
      - sys_rawio
    ports:
      - "2225:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.102
    hostname: linux_me_2
    privileged: true

volumes:
  msa_api:
  msa_db:
  msa_dev:
  msa_entities:
  msa_repository:
  msa_es:
  rrd_repository:
  msa_api_logs:
  msa_sms_logs:
  msa_bud_logs:
  msa_front:
  msa_svn:
  msa_ai_ml_db:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24
    driver_opts:
      encrypted: "true"
    